// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // Desktop platforms reuse the same Firebase project as Android.
      // firebase_core, firebase_auth, cloud_firestore, and firebase_storage
      // all support Linux and Windows desktop natively.
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return desktop;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANsl70LvRJ4jTemR-O9nUK1yBM7HIoSg',
    appId: '1:731338785867:android:81cc63e865752ca73b79ce',
    messagingSenderId: '731338785867',
    projectId: 'selectaapp',
    storageBucket: 'selectaapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANsl70LvRJ4jTemR-O9nUK1yBM7HIoSg',
    appId: '1:731338785867:web:9d0db626b42135cc3b79ce',
    messagingSenderId: '731338785867',
    projectId: 'selectaapp',
    authDomain: 'selectaapp.firebaseapp.com',
    storageBucket: 'selectaapp.firebasestorage.app',
  );

  /// Desktop (Linux / Windows) — same Firebase project as Android.
  /// Push notifications (firebase_messaging) are not available on desktop
  /// and are guarded in the app code with platform checks.
  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyBANsl70LvRJ4jTemR-O9nUK1yBM7HIoSg',
    appId: '1:731338785867:android:81cc63e865752ca73b79ce',
    messagingSenderId: '731338785867',
    projectId: 'selectaapp',
    storageBucket: 'selectaapp.firebasestorage.app',
  );
}
